##
# Sets up Gunicorn and configures Systemd to execute gunicorn_start script
##

# - name: Create a Deploy Directory if not exists
#   raw: mkdir /opt/django_bootstrap/deploy
#   become: yes

- name: Create the gunicorn_start script for running our app from systemd service
  template: src=gunicorn_start
                    dest={{ app_dir }}/deploy/gunicorn_start
  become: yes

- name: Make the gunicorn_start script executable
  raw: cd {{ app_dir }}/deploy; chmod +x gunicorn_start
  become: yes

- name: Make migrations
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py makemigrations "
  become: yes

- name: Migrate Database
  django_manage: app_path={{ app_dir }}
                                 command=migrate
                                 virtualenv={{ venv_dir }}

- name: Get all StaticFiles
  django_manage: app_path={{ app_dir }}
                                 command=collectstatic
                                 virtualenv={{ venv_dir }}
  become: yes
