###
##
# configure the server for the Django application
##
###
- include: f23.yml
- include: git.yml
- include: postgres.yml
- include: dependencies.yml
- include: gunicorn.yml
- include: nginx.yml
- include: selinux.yml
- include: systemd.yml
