##
# configure the server for the Django application
##
- include: f24.yml
- include: git.yml
- include: postgres.yml
- include: dependencies.yml
- include: migrations.yml
- include: nginx.yml
- include: gunicorn.yml
- include: systemd.yml
# needed incase you get a Nginx 502 Bad Gateway Error
- include: fix-502.yml
