##
# configure the server for the Django application
##
- include: f23.yml
- include: git.yml
- include: postgres.yml
- include: dependencies.yml
- include: migrations.yml
- include: nginx.yml
- include: gunicorn.yml
- include: systemd.yml
