##
# Configuration for Nginx web server
##
- name: Setting up Nginx Configuration
  dnf: name=nginx state=latest
  become: yes

- name: writing a nginx conf file for our Django app
  template: src=django_bootstrap.conf dest=/etc/nginx/conf.d/{{ app_name }}.conf
  become: yes
  notify:
    - restart nginx
